spring:
  application:
    name: clarium-sso

  # Session management
  session:
    store-type: none  # Don't persist sessions
    timeout: 1m       # Very short timeout for testing
    tracking-modes: cookie
    cookie:
      name: JSESSIONID
      http-only: true
      secure: false    # Set to true in production
      same-site: lax
      max-age: 300     # 5 minutes

  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 215b5640-18a9-4579-85f0-dee13df57b61
            client-secret: tuz8Q~Zda7W6IEDsnrucsYvol4QecDkM7J68lbu~
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/User.ReadBasic.All
            redirect-uri: http://localhost:8080/login/oauth2/code/
            client-name: Azure AD
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/discovery/v2.0/keys
            user-name-attribute: sub
            issuer-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/v2.0

  datasource:
    url: jdbc:sqlserver://10.2.1.4:52752;databaseName=employee-details;encrypt=false
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.clarium.sso@gmail.com
    password: tswdzlzgfwyaqank
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server configuration
server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        max-age: 1800
        same-site: lax

cors:
  allowed-origins: http://localhost:5050, http://localhost:5051, http://localhost:5052
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging for debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.clarium.clarium_sso.service.LogoutService: DEBUG

app:
  blocked-url: "http://localhost:8080"


